name: 'Auto get lex follower'

on: 
  schedule:
    - cron: "0 * * * *"
  watch:
    types: [started]
   
jobs:
  checking:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai          
    - name: Get log
      uses: actions/checkout@master
    - name: Chick in Api #Api调用
      run: | 
        echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./run.log 
        curl curl https://api.bilibili.com/x/relation/stat?vmid=777536 >> ./run.log
        echo >> ./run.log
        tail run.log #避免日志上传失败丢失日志
    - name: Commit #上传日志到仓库，可以自行修改 name 和 email
      env:
       NAME: moreant
       EMAIL: moreant@foxmail.com
      run: |
        git config --global user.email "actionbot@bot.com"
        git config --global user.name "actionbot"
        git add .
        git commit -m "update log" -a
    - name: Push log
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
